version: '2'
services:
  test-webpack:
    container_name: test-webpack
    image: node:7.5
    ports:
      - "8080:8080"
    command: bash -c "npm install && npm start"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
